name: Build and Deploy Angular Application

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: demo-app-angular
  CONTAINER_NAME: demo-app-angular

jobs:
  build:
    name: Build and Push Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: |
          echo "${{ secrets.ANGULAR_GHCR_PAT }}" | docker login ghcr.io \
          -u "${{ github.repository_owner }}" \
          --password-stdin

      - name: Build Docker Image
        run: |
          docker build \
          -t ghcr.io/${{ github.repository_owner }}/demo-app-angular:latest .

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/demo-app-angular:latest

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Create SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy Application
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'

          echo "========== LOGIN TO GHCR =========="

          echo "${{ secrets.ANGULAR_GHCR_PAT }}" | docker login ghcr.io \
          -u "${{ github.repository_owner }}" \
          --password-stdin

          echo "========== PULL IMAGE =========="

          docker pull ghcr.io/${{ github.repository_owner }}/demo-app-angular:latest

          echo "========== REMOVE OLD CONTAINER =========="

          docker rm -f demo-app-angular || true

          echo "========== CLEANUP =========="

          docker image prune -af

          echo "========== START NEW CONTAINER =========="

          docker run -d \
            --name demo-app-angular \
            --restart unless-stopped \
            -p 4200:80 \
            ghcr.io/${{ github.repository_owner }}/demo-app-angular:latest

          echo "========== RUNNING CONTAINERS =========="

          docker ps

          echo "========== AVAILABLE IMAGES =========="

          docker images

          echo "========== DEPLOYMENT SUCCESSFUL =========="

          EOF